# Generated by Django 4.2.6 on 2023-10-31 20:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, null=True, region='ES', unique=True)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Body_Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, null=True)),
                ('modelo_bk', models.CharField(max_length=20, null=True)),
                ('material', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.DateField()),
                ('marca', models.CharField(max_length=20, null=True)),
                ('modelo', models.CharField(max_length=20)),
                ('estilo', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Escape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, null=True)),
                ('modelo_escape', models.CharField(max_length=20, null=True)),
                ('material', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('modelo_coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.coche')),
            ],
        ),
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, null=True)),
                ('modelo_llanta', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('modelo_coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.coche')),
            ],
        ),
        migrations.CreateModel(
            name='Volante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, null=True)),
                ('modelo_volante', models.CharField(max_length=20, null=True)),
                ('material', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('modelo_coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.coche')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_bk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.body_kit')),
                ('modelo_coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_Coche', to='japanapp.coche')),
                ('modelo_escape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.escape')),
                ('modelo_llanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.llanta')),
                ('modelo_volante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.volante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='body_kit',
            name='modelo_coche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japanapp.coche'),
        ),
    ]
