# Generated by Django 4.2.6 on 2023-11-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japanapp', '0002_remove_proyecto_user_suspension_filtro'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='modelo_filtro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_filtro', to='japanapp.filtro'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='modelo_suspes',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_suspension', to='japanapp.suspension'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modelo_bk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_bk', to='japanapp.body_kit'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modelo_escape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_escape', to='japanapp.escape'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modelo_llanta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_llanta', to='japanapp.llanta'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modelo_volante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_volante', to='japanapp.volante'),
        ),
    ]
