# Generated by Django 4.2.6 on 2023-11-20 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japanapp', '0004_proyecto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modelo_filtro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_filtro', to='japanapp.filtro'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modelo_suspes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Modelo_suspension', to='japanapp.suspension'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
